### ISSUE TITLE
Hack for LA 2022 Holiday Party Planning 

### ISSUE THREAD

**Issue by kcoronel** [civictechstructure/party#20]
### Overview
Planning Hack for LA's 2022 in-person holiday party. 
**Saturday, December 10, 2022**
**Time: 6:00 - 9:00 PM**
[MeetUp RSVP Link](https://www.meetup.com/hackforla/events/290125124/)

Virtual Holiday Party
**Saturday, December 14, 2022**
**Time: 6:00 - 9:00 PM**
Zoom link: 

### Action Items
Potential venues list: 
_venues below have a liberal option for reserving space i.e. no charge for reserving_ 
- [Arts District Brewing](https://www.artsdistrictbrewing.com/private-events) 12pm - 2am 
   -  under 21 okay until 7pm
   -  send email using [this form](https://www.artsdistrictbrewing.com/private-events)

No's: 
- [82 LA](https://www.eightytwo.la/) 2pm - 2am 
    - No RSVP needed, first come first serve 
 - [Home Bound Brew Haus](https://www.homeboundbrewhaus.com/) 12pm - 12am 
    - no RSVP needed, first come first serve 
    - might be too "adult"
- [Angel City Brewery](https://angelcitybrewery.com/) 12pm - 2am 
    - send email using [this form ](https://angelcitybrewery.com/contact/event-rental/)
- [Boomtown Brew](https://www.boomtownbrew.com/about/) 12pm - 2am 
    - no RSVP needed, first come first serve 

### Resources/Instructions
[Holiday Party Google folder ](https://drive.google.com/drive/folders/15qg3TNeGsI0iBt4wuEb1cbM9N3wuC0NQ?usp=sharing)

**Comment by kcoronel** [comment]
Draft Invite ![Holiday Party](https://user-images.githubusercontent.com/38144130/195994147-056bb65b-0657-4109-9e49-c811372e9c87.png)

**Comment by kcoronel** [comment]
Comments for image: 
- Language updates 
- Location 
- Link to place 

Updated graphic for meet-up: 

![Holiday Party](https://user-images.githubusercontent.com/38144130/205456132-59f10d05-c3f1-45a7-a9d7-69cba8b3bb01.png)

**Comment by ExperimentsInHonesty** [comment]
stephen@pouringwithheart.com
Hi Stephen,

Back in 2019 we had a get-together for our all volunteer organization, Hack for LA, and had a great time.

![image](https://user-images.githubusercontent.com/37763229/205456071-56ebafe6-40cd-40a6-8fc2-a29d91410b4b.png)

We know you don't reserve tables on weekends, but thought we should give you a heads-up that we are going to be coming on Saturday the 10th and so far 20 people have Rsvp'd

Do you want us to let you know when the date gets closer how many people have rsvp'd?

Best,

photo-logo	
Bonnie Wolfe
Brigade Captain, Executive Director, Hack for LA
310-740-1161
Hack for LA is an official brigade of Code for America

**Comment by ExperimentsInHonesty** [comment]
We posted the event on Meetup on https://www.meetup.com/hackforla/events/290125124/
and messaged everyone via slack in general

**Comment by ExperimentsInHonesty** [comment]
Virtual party details
Date: 2022-12-14
Time: 6-9 pm pst
Zoom 4 
Zoom Registration
Zoom Authentication
Title: Hack for LA Holiday Party 🎉 VIRTUAL
Description:
Join us for a virtual get together of our HackforLA community! Filled with games and other fun activities. 
We look forward to seeing you there. Please reach out to us on the #admin slack channel for any questions or issues.

Slack message: 
Bonnie

`@channel` If you can't make our in person party, please  [RSVP for the 12-14 6PM PST global ](https://us06web.zoom.us/meeting/register/tZwrfuGrrDsrHN1v02ZoAmIUcWAeVvKRf5KK):globe_with_meridians: :desktop_computer: :tada: [virtual holiday party on zoom](https://us06web.zoom.us/meeting/register/tZwrfuGrrDsrHN1v02ZoAmIUcWAeVvKRf5KK)

Image used in the zoom meetup registration
![image](https://user-images.githubusercontent.com/37763229/205458183-9d185b1b-7251-4e07-9359-eb16ba8817cb.png)

Registration link
https://us06web.zoom.us/meeting/register/tZwrfuGrrDsrHN1v02ZoAmIUcWAeVvKRf5KK

**Comment by kcoronel** [comment]
Closing this issue as holiday party planning has been completed.

**Comment by ExperimentsInHonesty** [comment]
Stephen Dorame is our contact at Arts District
