### ISSUE TITLE
Summer 2024 Party

### ISSUE THREAD

**Issue by Rabia2219** [civictechstructure/party#22]
### Overview
This issue will help us coordinate planning for Hack for LA's Summer Picnic happening on July 13, 2024 at Cheviot Hills Recreation Area. 

### Action Items
- [x] Secure location and make deposit 
- [x] Create graphic for invites 
- [x] Create language for Slack posting 
- [x] Create a form for what people are bringing
   - [x] spreadsheet for what people will bring to picnic will show
      - category
      - item description
      - number of servings
      - Ingredients (for allergic purposes)
- [x] Create LinkedIn Invite Meeting

### Resources/Instructions
- [2024 Summer Party Folder](https://drive.google.com/drive/folders/1yT9EXR-d81qjwc2H9_4RA_thy_PgCp9S?usp=drive_link)
- Contribution Form 
   - [view](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/edit)
   - [edit](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/edit)
   - [responses in form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/edit#responses)
   - [responses in sheets (public)](https://docs.google.com/spreadsheets/d/1uwrrc3SCPRKSxB3qJMysBtJTK0tJWgzk0BehrZP9IrY/edit?resourcekey=&gid=55212534#gid=55212534)
   - preview version of responses: [see what other people are bringing](https://docs.google.com/spreadsheets/d/1uwrrc3SCPRKSxB3qJMysBtJTK0tJWgzk0BehrZP9IrY/preview)
- WIKI Page: https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Directions,-Parking-info-and-Pictures

#### View the picnic area
<details><summary>Image of picnic area</summary>

![image](https://github.com/civictechstructure/party/assets/37763229/18551d56-5cc7-4dda-acf4-59017fe89f80)
</details> 

[link to view the picnic area](https://www.google.com/maps/@34.0455848,-118.4123468,3a,75y,115.8h,90t/data=!3m7!1e1!3m5!1sSbq6gzt7wuK5f3EgPg-nZA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DSbq6gzt7wuK5f3EgPg-nZA%26cb_client%3Dmaps_sv.share%26w%3D900%26h%3D600%26yaw%3D115.80002874610106%26pitch%3D0%26thumbfov%3D90!7i16384!8i8192?coh=205410&entry=ttu)

#### Maps
- Address of event: 2551 Motor Ave., Los Angeles, CA 90064
- Cartoon map from park service https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/map.pdf
- [directions to parking area next to picnic](https://www.google.com/maps/dir//Parking+lot,+2459+Motor+Ave,+Los+Angeles,+CA+90064/@34.0454435,-118.4125289,18z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2bbc1ddaf5edf:0xf585812f0d29eb59!2m2!1d-118.4122027!2d34.0457214!3e0?entry=ttu) - When this lot is full, use the main lot.
- [directions to overflow parking in the main lot](https://www.google.com/maps/place/2551+Motor+Ave+Parking/@34.0471309,-118.4086059,17z/data=!4m6!3m5!1s0x80c2bbc2769b2d45:0x9f035fa59a4e957d!8m2!3d34.04679!4d-118.4084493!16s%2Fg%2F11f3sfhh9c?entry=ttu) - This is the main parking for the park. It's a [5-min walk between the main parking lot and the picnic area](https://www.google.com/maps/dir/2551+Motor+Ave+Parking,+Parking+lot,+2551+Motor+Ave,+Los+Angeles,+CA+90064/'34.0454435,-118.4125289'/@34.0467563,-118.4117923,18z/data=!3m1!4b1!4m12!4m11!1m5!1m1!1s0x80c2bbc2769b2d45:0x9f035fa59a4e957d!2m2!1d-118.4084493!2d34.04679!1m3!2m2!1d-118.4125289!2d34.0454435!3e2?entry=ttu)

#### graphics for invites/forms
- LinkedIn
  - linkedin Event 'Banner' Size: 16:9 ratio, preferably 1600 x 900 pixels. [Article with banner size advice](https://www.linkedin.com/pulse/linkedin-image-size-guide-julie-thomas-tftwc)
      <details><summary>LinkedIn Image</summary>

       [Where to Edit](https://www.canva.com/design/DAGHPFhKk9M/U5YiVbg4z2m3bgAVA2OlPw/edit?utm_content=DAGHPFhKk9M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

      Use for posting:
       ![Hack for LA Picnic Graphic - LinkedIn](https://github.com/civictechstructure/party/assets/38144130/c7e8ed85-ef3c-475a-b10e-4e4add88f4b2)
      </details> 

- Google Forms
  - image needed for google form banner 1600x400
       <details><summary>Google Forms Image</summary>

       [Where to edit](https://www.canva.com/design/DAGHS2Je3Lw/OBY7z6tioXRFA-OfnJ1VEw/edit?utm_content=DAGHS2Je3Lw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

       ![Header for Google Forms - Hack for LA Picnic](https://github.com/civictechstructure/party/assets/38144130/981010d0-95fe-4224-a6ae-b4acdb930943)
      </details> 
- Other
[Alphabetical list of cities for California and Southern California](https://www.landsmart.com/index.php?option=com_content&view=article&id=161&Itemid=113)
- [Cheviot Hills](https://www.laparks.org/reccenter/cheviot-hills)
- [Info about reserving PDF](https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/picnic-areas-info-and-agreement-24.pdf)
   - Applications accepted for the full year starting January 2nd
   - email to reserve on the above document
- [Permit Application](https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/permit-application-agreement-24.pdf)

**Comment by Rabia2219** [comment]
- start looking at parks available for booking in the Playa Vista area
  - https://playavista.com/active-outdoors/parks-rec/
  - https://playavista.com/contact-us/
#### Correct email for correspondence
  - askpvpal@seabreezemgmt.com

**Comment by Rabia2219** [comment]
- July 13th and 20th: 
  - Fountain Park, no restrooms, only grass area, $350/4hrs, $750 deposit
- July 6th and 27th:
   - Concert Park, restrooms, $500/4hrs, $750 deposit
   - There are tables and it is also ok to bring in more

phone: 310.437.6070
email: maricela.sandoval@seabreezemgmt.com (for info on how to reserve)

**Comment by Rabia2219** [comment]
#### Notes for draft proposal

- determination letter and link (https://apps.irs.gov/app/eos/)
- bathrooms
- beach chairs, picnic blanket, lawn games (fast four, corn hole, frisbee, ring toss, giant Jenga etc.)
- no vendors
- potluck, will be taken back
- 4 folding tables for food (all precooked)
- invite only to HfLA members (security)
- parking (car pool)
- alcohol free
- look up insurance from last party issue
- premade badges
- look at draft and suggest security

**Comment by Rabia2219** [comment]
#### Beach Option

- https://beaches.lacounty.gov/dockweiler-beach-fire-pits/
- https://www.laparks.org/reservations/griffith-park-picnic-permits

**Comment by ExperimentsInHonesty** [comment]
We ended up at Cheviot Hills Recreation Area 
[[Facility Rental Information Picnic Areas map]](https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/map.pdf)

**Comment by ExperimentsInHonesty** [comment]
Form will ask:
- Name
- Email
- Slack
- Phone (for texting)
- Preferred method of contact
- category
- item description
- number of servings
- Ingredients (for allergic purposes)

Publish a spreadsheet of the following columns
- category
- item description
- number of servings
- Ingredients (for allergic purposes)

**Comment by ExperimentsInHonesty** [comment]
graphic for invite
linkedin Event 'Banner' Size: 16:9 ratio, preferably 1600 x 900 pixels.Mar 5, 2024 https://www.linkedin.com/pulse/linkedin-image-size-guide-julie-thomas-tftwc

**Comment by kcoronel** [comment]
2551 Motor Ave., Los Angeles, CA 90064
https://www.laparks.org/sites/default/files/reccenter/cheviot-hills-recreation-center/media/map.pdf

[Google Map link](https://www.google.com/maps/dir//2551+Motor+Ave,+Los+Angeles,+CA+90064/@34.0460642,-118.4922534,12z/data=!4m8!4m7!1m0!1m5!1m1!1s0x80c2bbc1b6eaeb13:0xf78e201c79915b6c!2m2!1d-118.4098522!2d34.0460917?entry=ttu)

**Comment by Rabia2219** [comment]
#### Meetup Post Draft

For Reference: [2023 Holiday Party Meetup Post
](https://www.meetup.com/hackforla/events/296820230/)

**🌞 Hack for LA Summer Party! 🌞**

[Image with date, time, location]

Join us for a fun-filled summer potluck party in the park! Hack for LA members, friends, families, and well behaved pets (dogs must be leashed) are all welcome to attend. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

**What to Bring:**

- Food & Drinks: Please bring your favorite dish and beverages to share.
- Games & Activities: Feel free to bring any games or activities you'd like to enjoy with others.

**Contribution Form:**

To help us organize the event better, please fill out the [contribution form] with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks.

**Not a Member Yet?**

Our party is only open to members.  If you are interested in volunteering with us, we encourage you to attend our [last onboarding session in June (Tuesday, June 18th 2024](https://www.meetup.com/hackforla/events/298147579/)), so you can join our community and attend the party. 

Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!

**Comment by Rabia2219** [comment]
#### Slack Post Draft
:mega: Hey Everyone! We're excited to announce our upcoming Summer potluck Party!

:tada: Join us for a fun day at the park, filled with great food, drinks, games, and awesome company. Friends, families, and pets (must be on a leash) are welcome, so feel free to bring them along!

:date: Date: July 13th, 2024
:clock3: Time: 12 PM PST
:round_pushpin: Location: Cheviot Hills Recreation Area, Los Angeles

:white_check_mark: Find all the details on [Meetup] and RSVP now!

**Comment by Rabia2219** [comment]
#### LinkedIn Post Draft

🌞 Join Us for the Hack for LA Summer Party! 🌞

🎉We're thrilled to invite you to our summer potluck party in the park! This is a fantastic opportunity to relax, connect, and enjoy great food and company. Friends, families, and pets (must be on a leash) are welcome to join in the fun!

📅 Date: [Insert Date]
🕒 Time: [Insert Time]
📍 Location: [Insert Park Name], Los Angeles

✅Find the details on [Meetup] and RSVP now!

P.S. Our party is only open to members.  If you are interested in volunteering with us, we encourage you to attend our [last onboarding session in June (Tuesday, June 18th 2024](https://www.meetup.com/hackforla/events/298147579/)), so you can join our community and attend the party.

**Comment by kcoronel** [comment]
### Linkedin

[Where to Edit](https://www.canva.com/design/DAGHPFhKk9M/U5YiVbg4z2m3bgAVA2OlPw/edit?utm_content=DAGHPFhKk9M&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

Use for posting:
![Hack for LA Picnic Graphic - LinkedIn](https://github.com/hackforla/admin/assets/38144130/c7e8ed85-ef3c-475a-b10e-4e4add88f4b2)

**Comment by ExperimentsInHonesty** [comment]
image needed for google form banner 

1600x400

**Comment by kcoronel** [comment]
### Google Forms

[Where to edit](https://www.canva.com/design/DAGHS2Je3Lw/OBY7z6tioXRFA-OfnJ1VEw/edit?utm_content=DAGHS2Je3Lw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

![Header for Google Forms - Hack for LA Picnic](https://github.com/hackforla/admin/assets/38144130/981010d0-95fe-4224-a6ae-b4acdb930943)

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/admin/assets/37763229/18551d56-5cc7-4dda-acf4-59017fe89f80)

[link to view the picnic area](https://www.google.com/maps/@34.0455848,-118.4123468,3a,75y,115.8h,90t/data=!3m7!1e1!3m5!1sSbq6gzt7wuK5f3EgPg-nZA!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DSbq6gzt7wuK5f3EgPg-nZA%26cb_client%3Dmaps_sv.share%26w%3D900%26h%3D600%26yaw%3D115.80002874610106%26pitch%3D0%26thumbfov%3D90!7i16384!8i8192?coh=205410&entry=ttu)

[directions to parking area next to picnic](https://www.google.com/maps/dir//Parking+lot,+2459+Motor+Ave,+Los+Angeles,+CA+90064/@34.0454435,-118.4125289,18z/data=!4m9!4m8!1m0!1m5!1m1!1s0x80c2bbc1ddaf5edf:0xf585812f0d29eb59!2m2!1d-118.4122027!2d34.0457214!3e0?entry=ttu) - When this lot is full, use the main lot.

[directions to overflow parking in the main lot](https://www.google.com/maps/place/2551+Motor+Ave+Parking/@34.0471309,-118.4086059,17z/data=!4m6!3m5!1s0x80c2bbc2769b2d45:0x9f035fa59a4e957d!8m2!3d34.04679!4d-118.4084493!16s%2Fg%2F11f3sfhh9c?entry=ttu) - This is the main parking for the park. It's a [5-min walk between the main parking lot and the picnic area](https://www.google.com/maps/dir/2551+Motor+Ave+Parking,+Parking+lot,+2551+Motor+Ave,+Los+Angeles,+CA+90064/'34.0454435,-118.4125289'/@34.0467563,-118.4117923,18z/data=!3m1!4b1!4m12!4m11!1m5!1m1!1s0x80c2bbc2769b2d45:0x9f035fa59a4e957d!2m2!1d-118.4084493!2d34.04679!1m3!2m2!1d-118.4125289!2d34.0454435!3e2?entry=ttu)

**Comment by ExperimentsInHonesty** [comment]
https://linkedin.com/in/bonnieawolfe

**Comment by Rabia2219** [comment]
- For the LinkedIn event, we will need a privacy policy on how we will use the invitees information

**Comment by Rabia2219** [comment]
#### Invite Post Draft
[Image with date, time, location]

**🌞 Hack for LA Summer Potluck Picnic! 🌞**

Join us for a fun-filled summer potluck picnic in the park! Hack for LA members, friends, families, and well-behaved pets are all welcome to attend (dogs must be leashed)*. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

**Mark Your Calendar**

:date: Date: July 13th, 2024
:clock3: Time: 12 PM - 3 PM PST
:round_pushpin: Location: Cheviot Hills Recreation Area, Los Angeles (Picnic Area 2)

**What to Bring:**

- Food & Drinks*: Please bring your favorite dish and beverages to share.
- Games & Activities*: Feel free to bring any games or activities you'd like to enjoy with others.

**Contribution Form:**

To help us organize the event better, please fill out the [contribution form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/viewform) with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks.

**Picnic Area Details**



**Let Us Know You're Coming**

Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!

✅ [RSVP]* now!
*If you're not already connected, make sure to [connect with Bonnie](https://linkedin.com/in/bonnieawolfe) on LinkedIn to receive the invite for the party

**Not a Member Yet?**

Our party is only open to members.  If you are interested in volunteering with us, we encourage you to attend our [last onboarding session in June (Tuesday, June 18th 2024](https://www.meetup.com/hackforla/events/298147579/)), so you can join our community and attend the party. 


*[Cheviot Hills Recreation Center Regulations](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Regulations)

**Comment by ExperimentsInHonesty** [comment]
Slack post sent 11:46 am 2024-06-25 in general channel

```
@channel

:sun_with_face: Hack for LA Summer Potluck Picnic! :sun_with_face:
Join us for a fun-filled summer potluck picnic in the park! Hack for LA members, friends, families, and well-behaved pets are all welcome to attend (dogs must be leashed)*. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

Let Us Know You're Coming
Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!
:white_check_mark: RSVP on meetup now!

:date: Date: July 13th, 2024
:clock3: Time: 12 PM - 3 PM PST
:round_pushpin: Location: Cheviot Hills Recreation Area, Los Angeles (Picnic Area 2)

What to Bring:
Food & Drinks*: Please bring your favorite dish and beverages to share. To help us organize the event better, please check out what other [people are bringing](https://docs.google.com/spreadsheets/d/1uwrrc3SCPRKSxB3qJMysBtJTK0tJWgzk0BehrZP9IrY/preview) and then fill out the [contribution form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/viewform) with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks. If you can't bring anything, no worries,  we have an option for that on the contribution form.

Games & Activities*: Feel free to bring any games or activities you'd like to enjoy with others.

Other Picnic Area Details
[Maps, pictures and details](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Directions,-Parking-info-and-Pictures)

---
*[Cheviot Hills Recreation Center Regulations](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Regulations)

If you have questions, please write them in the replies on this Slack message.
```

<details><summary>viewable post</summary>

**:sun_with_face: Hack for LA Summer Potluck Picnic! :sun_with_face:**
Join us for a fun-filled summer potluck picnic in the park! Hack for LA members, friends, families, and well-behaved pets are all welcome to attend (dogs must be leashed)*. It's a great opportunity to relax, socialize, and enjoy the summer weather together.

**Let Us Know You're Coming**
Come out, have fun, and connect with fellow Hack for LA members. We look forward to seeing you there!
:white_check_mark: RSVP on meetup now!

:date: Date: July 13th, 2024
:clock3: Time: 12 PM - 3 PM PST
:round_pushpin: Location: Cheviot Hills Recreation Area, Los Angeles (Picnic Area 2)

**What to Bring:**
Food & Drinks*: Please bring your favorite dish and beverages to share. To help us organize the event better, please check out what other [people are bringing](https://docs.google.com/spreadsheets/d/1uwrrc3SCPRKSxB3qJMysBtJTK0tJWgzk0BehrZP9IrY/preview) and then fill out the [contribution form](https://docs.google.com/forms/d/1maxqwbZQLesyZ6y2eypdriadWMTNYnYCb-XtfAdDlr0/viewform) with the items you plan to bring. This will help avoid duplicates and ensure we have a variety of food and drinks. _If you can't bring anything_, no worries, we have an option for that on the contribution form.

Games & Activities*: Feel free to bring any games or activities you'd like to enjoy with others.

**Other Picnic Area Details**
[Maps, pictures and details](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Directions,-Parking-info-and-Pictures)

---
*[Cheviot Hills Recreation Center Regulations](https://github.com/civictechstructure/party/wiki/Cheviot-Hills-Recreation-Center-Regulations)

If you have questions, please write them in the replies on this Slack message.
</details>

**Comment by kcoronel** [comment]
Learnings: don't add a lot of information to LinkedIn invite and limit to one link so that we can navigate people to the MeetUp RSVP page. At Admin meeting we have a discrepancy between folks who RSVP'd in LinkedIn and those who have RSVP'd on Meet Up.

**Comment by senakim18** [comment]
9/12: Bonnie (from [team@civictechstructure.org](mailto:team@civictechstructure.org)) sent thank you & follow-up emails to attendees of 2024 Summer Potluck who donated & didn't donate (respectively). Email templates & notes can be found [here](https://drive.google.com/drive/folders/1jWwFAgFLNPz3blFW3IxkO8Nsd3CpH2m2).

11/7: Bonnie (from [team@civictechstructure.org](mailto:team@civictechstructure.org)) sent thank you emails to Shienny & Saumil who donated after receiving the email. Bonnie also sent a thank you LinkedIn message to Gerald Yao.
